// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-variants/Colore.tsx": () => import("../components/mockups/portfolio-variants/Colore.tsx"),
  "./components/mockups/portfolio-variants/Editorial.tsx": () => import("../components/mockups/portfolio-variants/Editorial.tsx"),
  "./components/mockups/portfolio-variants/Luxe.tsx": () => import("../components/mockups/portfolio-variants/Luxe.tsx"),
  "./components/mockups/portfolio-variants/Minimaliste.tsx": () => import("../components/mockups/portfolio-variants/Minimaliste.tsx"),
  "./components/mockups/portfolio-variants/Premium.tsx": () => import("../components/mockups/portfolio-variants/Premium.tsx"),
  "./components/mockups/portfolio-variants/TechSombre.tsx": () => import("../components/mockups/portfolio-variants/TechSombre.tsx")
};
